"""initial

Revision ID: d77c9bad653a
Revises: 
Create Date: 2022-02-03 10:14:23.635218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77c9bad653a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_budget', sa.Integer(), nullable=True),
    sa.Column('building', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=64), nullable=True),
    sa.Column('course_credits', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('instructor',
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('instructor_name', sa.String(length=64), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.PrimaryKeyConstraint('instructor_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], ),
    sa.ForeignKeyConstraint(['sec_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('sec_course',
    sa.Column('sec_course_id', sa.Integer(), nullable=False),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['sec_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('sec_course_id')
    )
    op.create_table('teachers',
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.instructor_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('instructor_id', 'section_id')
    )
    op.create_table('teaches',
    sa.Column('teaches_id', sa.Integer(), nullable=False),
    sa.Column('sec_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.instructor_id'], ),
    sa.ForeignKeyConstraint(['sec_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('teaches_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teaches')
    op.drop_table('teachers')
    op.drop_table('sec_course')
    op.drop_table('student')
    op.drop_table('instructor')
    op.drop_table('course')
    op.drop_table('section')
    op.drop_table('department')
    # ### end Alembic commands ###
